### ISSUE TITLE
fbxctest: v0.1 Checklist

### ISSUE THREAD

**Issue by lawrencelomax** [facebook/idb#294]
There are a number of things that should be necessary for a v0.1 of `fbxctest`. This list is probably not exhaustive.
- [ ] Using [`otest-shim` from inside `fbxctest` for fast logic tests](https://gist.github.com/lawrencelomax/70660eec687869ec1873816050fbf396).
- [x] Adding `fbxctest` to the `build.sh`
- [ ] e2e tests for the executable, [like the ones for `fbsimctl`](https://github.com/facebook/FBSimulatorControl/tree/master/fbsimctl/cli-tests).
- [ ] A `hombrew` formula.
- [ ] Detection of the `.xctest` type, so that the running strategy can be chosen at runtime.
- [ ] Removal of `launch_xctest` and `XCTestBootstrap` from `fbsimctl`.
- [x] Listing of Mac OS X Test Targets
- [x] Confirmation of Signed App & Bundle for > Xcode 8 Beta 4.

**Comment by plu** [comment]
Do you already have some Xcode project and scheme for `fbxctest` somewhere in your internal repository? I couldn't find any here on GitHub, yet.

**Comment by lawrencelomax** [comment]
Looks like I didn't check it in. Will fix that shortly.

**Comment by plu** [comment]
Thank you! Maybe I will find a bit time here and there to help with `fbxctest`.
